apiVersion : apps/v1
kind: Deployment
metadata:
  name: jayashrimahalespringbootapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jayashrimahalespringbootapp 
  template:
    metadata:
      labels:
        app: jayashrimahalespringbootapp  
    spec:
      containers:
        - name: jayashrimahalespringbootapp 
          image: jayashrimahale22/kubernetes-demo:kubernetes-demo
          ports:
          - containerPort: 80
